apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp-pod
spec:
  containers:
  - name: myapp-containers
    image: busybox:1.28
    env:
    - name: FIRSTNAME
      value: "Abhiram"
  initContainers:
  - name: init-myservice
    image: busybox:1.28
    command: ['sh' , '-c']
    args: ['until nslookup myservice.default.svc.cluster.local; do echo waiting for the service to be up ; sleep 2; done']