apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: pod-reader
rules:
  - apiGroups: [""] #indicate core api group
    resources: ["pods"]  #permission to 
    verbs: ["get", "watch", "list"] #access types