apiVersion: v1
kind: Pod
metadata:
  labels:
    env: demo
  name: nginx-pod
spec:
  containers:
  - image: nginx
    name: nginx-pod
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: disktype
            operator: In
            values:
            - hdd        


